apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

group = 'com.github.onlinerby'
version = '1.14.1'
description = 'An implementation of tap targets from the Material Design guidelines for feature discovery'

android {
    namespace = "com.getkeepsafe.taptargetview"
    compileSdkVersion defCompileSdkVersion
    buildToolsVersion defBuildToolsVersion

    defaultConfig {
        minSdkVersion defMinSdkVersion
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    api "androidx.annotation:annotation:1.8.1"
    api "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.core:core:1.13.1"
}

afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                from components.findByName('release')
                groupId = 'com.getkeepsafe.taptargetview'
                artifactId = 'TapTargetView'
                version = '1.14.1'
            }
        }
    }
}