buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }
}

ext {
    defBuildToolsVersion = '34.0.0'
    defMaterialVersion = '1.0.0'
    defCompileSdkVersion = 34
    defMinSdkVersion = 21
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
